### ISSUE TITLE
Support compiling gcc

### ISSUE THREAD

**Issue by bodgergely** [rafalmiel/cykusz-rs#1]

**Comment by bodgergely** [comment]
any update on this?

**Comment by rafalmiel** [comment]
Work in progress. Will keep you posted

**Comment by bodgergely** [comment]
any update on this?

**Comment by rafalmiel** [comment]
Still WIP. Need to add filesystem first

**Comment by bodgergely** [comment]
👌

**Comment by bodgergely** [comment]
you have filesystem

**Comment by bodgergely** [comment]
Nice, after 2 and half years, the issue got closed! Nice job!

**Comment by rafalmiel** [comment]
Thanks buddy, please test and report issues, hope you are happy with this feature!
